from pyutil.myerror.MyError import MyError



class NameHasNotDatetimeError(MyError):
    """名前にDatatimeの情報がない"""

    